services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: iris-postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -p 5432 -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    container_name: iris-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5454:5454'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
